lib/LWP/UserAgent.pm
t/base/default_content_type.t

If you say:
$ua->default_header('Content-Type' => 'foo');
$ua->post($url, Content => 'string');
You very likely mean for the request to use the provided
default Content-Type (in this case: 'foo').
This change allows that to happen, while still letting the
following forms override the default Content-Type with
'x-www-form-urlencoded' (since that makes sense as the body
of the request is being encoded for you):
$ua->post($url, \%form);
$ua->post($url, \@form);
$ua->post($url, Content => \%form);
$ua->post($url, Content => \@form);

Let default_header(Content-Type => '...') work for post/put

---

Makefile.PL
lib/LWP/Protocol.pm
lib/LWP/UserAgent.pm

Update all of the places where we had a raw ```eval``` and replace it with a ```try {} catch {};``` block.
There was also a ```UNIVERSAL::isa()``` call that got switched to ```->isa()``` instead.  These changes require adding two prerequisites, ```Scalar::Util``` and ```Try::Tiny```.
While the changes test properly, they did require a few changes to the loading of protocol packages.
A full review by a few is needed.

Eval -> Try::Tiny

---

lib/LWP/Protocol/http.pm
t/net/cache-timeouts.t

Hiya!
This is a fix for https://rt.cpan.org/Public/Bug/Display.html?id=110893 . Basically, timeout is only set when the socket is created, so if a socket is reused, timeout wasn't updated.
I tested with this script: https://gist.github.com/nfg/2a8ef485b004524fe163
Cheers!

Update "timeout" when reusing sockets

---

lib/LWP/UserAgent.pm
t/base/ua.t

As was pointed out in Issue #107 an error was introduced with moving from raw ```eval```s to ```Try::Tiny``` within ```LWP::UserAgent->simple_request```.
This fix should accurately trap the errors and return the error response when found.  Also, a few new tests were added to ```t/base/ua.t``` to test the ways in which the call to ```->prepare_request``` can die from within ```->simple_request```.

Fix incorrect usage of Try::Tiny

---

lib/LWP/UserAgent.pm

When making use of Try::Tiny, a few bugs were introduced. This PR should remove the last potential bug where within the ```catch``` block there was a ```next CHALLENGE```.

Clean up the request method and fix the "next" call within the catch

---

lib/LWP/Protocol/cpan.pm
lib/LWP/Protocol/data.pm
lib/LWP/Protocol/file.pm
lib/LWP/Protocol/ftp.pm
lib/LWP/Protocol/gopher.pm
lib/LWP/Protocol/http.pm
lib/LWP/Protocol/mailto.pm
lib/LWP/Protocol/nntp.pm
lib/LWP/Protocol/nogo.pm
lib/LWP/RobotUA.pm
lib/LWP/UserAgent.pm

Throughout the dist there are several instances where calling constant functions in the HTTP::Status dist are done via ```&func```. This could be done via ```func``` instead as there's no need to pass ```@_``` through to those functions.
This goes towards fixing #110

Make calls to constant HTTP::Status functions no longer use &FUNC form

---

bin/url-minder
lib/LWP/ConnCache.pm
lib/LWP/Protocol/data.pm
lib/LWP/Protocol/file.pm
lib/LWP/Protocol/ftp.pm
lib/LWP/Protocol/gopher.pm
lib/LWP/Protocol/http.pm
lib/LWP/Protocol/loopback.pm
lib/LWP/Protocol/mailto.pm
lib/LWP/Protocol/nntp.pm
lib/LWP/Protocol/nogo.pm
lib/LWP/Simple.pm

The ```use vars``` pragma is in place in many areas.  Where it makes sense, these have been converted to either ```use base 'Foo';``` or by declaring variables with ```our @EXPORT_OK = qw();``` or similar.
This PR should allow us to close #113

remove usage of use vars pragma

---

t/base/default_content_type.t

If [HTTP::Message](https://metacpan.org/pod/HTTP::Message) prior to version ```6.07``` is installed, we can't send hash or array references through to the ```content``` portion of the request.
Since this test set is specifically testing the differences in the default headers when passing different types of content, we need to skip a few tests when we detect that [HTTP::Message](https://metacpan.org/pod/HTTP::Message) versions 6.00, 6.01, 6.02, 6.03, 6.04, 6.05, or 6.06 are installed.
We can remove these skips later if we decide to up the prerequisite version of [HTTP::Message](https://metacpan.org/pod/HTTP::Message).

skip tests pre HTTP::Message 6.07

---

README.md
lib/LWP/UserAgent.pm

Update the documentation to make it clear that certain uses of the ```->put()``` method require at least HTTP::Message 6.07.
Also, clean up the documentation a bit to make it easier to find the methods in their ```=head2``` directive rather than multiple ```=item``` lines.

Doc differences for HTTP::Message < 6.07

---

README.md
dist.ini
lib/LWP/ConnCache.pm
lib/LWP/MemberMixin.pm
lib/LWP/Protocol.pm
lib/LWP/RobotUA.pm
lib/LWP/Simple.pm
lib/LWP/UserAgent.pm

Update all documentation in all modules (where documentation already exists) to move individual methods/functions/attributes up to the ```=head2``` level.  No longer have an item for each way to the call the function, but rather have those as example code below the new heading.
Try to have examples that more accurately describe how the functions work.  A lot more cleaning needs to be done and alphabetizing the lists needs to happen, but I think this is a good first step.

Update documentation to be a little cleaner

---

bin/lwp-download
bin/lwp-dump
bin/lwp-mirror
bin/lwp-request

This would address issue #184 
* Gets rid of the ```-w``` flag.
* Adds ```use strict;```
* Adds ```use warnigns;```
* Defines all variables where necessary,
* Cleans up code with perltidy.

use strict and warnings in all bin files and perltidy them

---

Changes
Makefile.PL
lib/LWP/UserAgent.pm
t/10-attrs.t

This PR should help with: https://github.com/libwww-perl/libwww-perl/issues/157
In ```->credentials``` in ```LWP::UserAgent``` we do ```my $netloc = lc(shift);```. This value could be undefined and when it's so, it causes warnings.
This is a proposal for a fix for that, ```my $netloc = lc(shift || '');``` but I can see going with other options as well.  Please review this and supply your thoughts.
Also, I started another test file ```t/10-attrs.t``` to allow us to start exercising every attribute to hopefully get the coverage up a bit and to help us when fixing documentation later.
-- Chase

lc() on possibly undefined value in ->credentials

---

lwpcook.pod

POST example doesn't work with http. rt.cpan.org now requires https.
Explicitly note that HTTP::CookieJar::LWP is a separate install.
Large document example URL no longer valid.  Replace with different site.

minor changes to make examples work; clarification of external module

---

t/local/get.t

This commits adds minimal tests for the get & head functional interface.
It extends the file that was already testing getprint & getstore.

Add tests for the "get" & "head" functions

---

bin/lwp-mirror

`lwp-mirror` was the last place using `Getopt::Std`.

entirely move away from Getopt::Std; fixes #200

---

lib/LWP/Protocol/http.pm

Prior to this change a HTTPS connection would not get additional error
information added to the status string. Compare the $@ contents for the
"Connection refused" case with IO::Socket::INET which was displayed:
```
IO::Socket::INET: connect: Connection refused
```
... and IO::Socket::SSL where the information was lost:
```
Connection refused
```

Include unmatched connect error in status string.

---

lib/LWP/Protocol/file.pm

`LWP::Protocol::file` can open existent file from `file://` scheme. However, current version of LWP uses `open FILEHANDLE,EXPR` and it has ability to execute arbitrary command as below:
```
$ touch '|echo vulnerable'
$ GET 'file:|echo vulnerable'
Use of uninitialized value $bytes in numeric gt (>) at /usr/share/perl5/LWP/Protocol/file.pm line 137.
vulnerable
```

Don't use insecure `open FILEHANDLE,EXPR`

---

lib/LWP/Protocol.pm
lib/LWP/Protocol/gopher.pm
lib/LWP/Protocol/http.pm
lib/LWP/UserAgent.pm

Not that it would really matter in these particular cases, but `tr` is much faster than `s` in trivial cases like these. And may result in (subjectively) cleaner code.

Use tr/// instead of s/// where appropriate

---

lib/LWP/Protocol/http.pm

Removing vars pragma usage in PR #114 and replacing it with `use base` had unwanted side-effects.
`@ISA` did not look for external dependencies whereas`use base` does.
If the user is in a directory in which he does not have read access and the package does not exist externally, this is an "other error" and Perl aborts:
```stat("./LWP/Protocol/http/SocketMethods.pm", 0x7fff176b5990) = -1 EACCES (Permission denied)```

revert vars pragma usage removal to not look for external dependencies

---

lib/LWP/UserAgent.pm
t/base/ua_handlers.t

The documentation of the `request_prepare` handler says:
The method can assign a new request object to $_[0] to replace the
request that is sent fully.
but that didn't work before this commit.

fix run_handlers to allow assigning to the request / response

---

lib/LWP/Protocol/http.pm

This matches with the other hash accessors in this block and should
prevent errors from downstream code that relies on `$self->{ua}` not
being blessed yet.
Fixes #280 
I should mention I have done no digging whatsoever into why this error is happening, but the code was inconsistent: It looks like LWP has always used hash accessors in this constructor, and never assumed that it was a blessed object passed-in.

use hash access for send_te

---

lib/LWP/Protocol.pm

Revert to raw eval in a case where the move to Try::Tiny seems to
have caused a regression where file handles are held open and the
limit for the number of open file handles is reached in a case
where the app requests a file. That file is saved and the req
opened the hostfile and that file remains open.
This behavior happens on every version of Perl lower than 5.18.

Too Many Open File Handles

---

xt/author/live/jigsaw/redirect-post.t

This shows that the module follows RFC 7231, sections 6.4.4 and 6.4.7
regarding 307 and 303 redirects. The current behavior is not a bug at
this point.
resolves #42, resolves #129

add a jigsaw test for 307 redirects

---

.travis.yml
Changes
lib/LWP/UserAgent.pm
xt/author/live/jigsaw/redirect-post.t

Altered the regular expression that checked for a sane-ish looking
URL for our proxy host:
if $url =~ /^https?:/ && $url !~ m,^https?://\w,;
Given this expression, a proxy host in the form of
http://[::1]:33485/ would fail because it starts with a left bracket.
The expression above has been altered to:
if $url =~ /^https?:/ && $url !~ m,^https?://[\w[],;
Which will allow it to begin with a word character or a left bracket.
This will resolve issue #237

Allow IPv6 proxy hosts starting with [.

---

Changes
t/base/protocols/nntp.t

Test::RequiresInternet doesn't seem to handle the case of nntp.perl.org
going down.  This breaks everyone's tests.
Fixes #307

SKIP nntp test for now

---

lib/LWP/UserAgent.pm

This example references a non-existent method `remove_handlers`. It should call `remove_handler` with no arguments to remove all handlers instead.

Fix documentation for removing all handlers

---

lib/LWP/UserAgent.pm
t/local/http.t

The ticket talks about "basic parameter validation". I think we only need to make sure the second arg is there. No need to check the URL as that will be done when we GET the file.
Closes #304

Make file arg for mirror mandatory #304

---

lib/LWP/UserAgent.pm
t/local/http.t

After GH#326 we were no longer able to mirror to files called '0'
Now we check for length and definedness rather than truthfullness
And I added tests

Allow mirroring to files called '0'

---

Changes
lib/LWP/UserAgent.pm
t/base/default_content_type.t
t/base/ua.t
t/local/http.t

Much like the previously added `put` method, the `patch` method will
require a specific version of HTTP::Request::Common. This time, though,
we will need at least version 6.12.
This is largely a copy-paste of the already added `put` method. All of
the current tests we have in place that test the `put` method were
duplicated for the new `patch` method. The same logic gate that only
tests when we have the proper version of HTTP::Request::Common was added
for the 6.12 check.
This makes LWP::UserAgent a bit simpler to work with RESTful endpoints
in that we now directly support the most common HTTP verbs: `HEAD`,
`GET`, `DELETE`, `PUT`, `POST`, `PATCH`.
Fixes #116

Add the patch method to LWP::UserAgent.

---

lib/LWP/UserAgent.pm

Omitting this blank line makes certain POD parsers believe that the
following line is still a part of the heading. This can be seen on
metacpan.org, for instance:

Add blank line after POD heading for patch method

---

Changes
lib/LWP/UserAgent.pm
t/local/http.t

The change in 6.45 had a side effect of making it look at max_redirect only when the Location header is set.
The libapache2-mod-perl2 test suite implements a test server that answers with HTTP code 303 without including such a header.
RFC 7231 is not very clear on whether Location is required, although
the response doesn't make much sense without it.
Some googling reveals this is not a new question.
https://stackoverflow.com/questions/16194988/for-which-3xx-http-codes-is-the-location-header-mandatory
For the sake of robustness I suppose libwww-perl needs to be fixed.
Bug-Debian: https://bugs.debian.org/962904

Fix a looping regression for 303 responses without a Location header

---

Changes
t/redirect.t

Require network testing enabled for t/redirect.t

---

Changes
lib/LWP/UserAgent.pm
t/base/ua.t

This is a rebased and slightly edited version of https://github.com/gisle/libwww-perl/pull/3 by @demerphq 
Audited and fixed any potential hash order dependency bugs in
LWP::UserAgent. I replaced all the uses of each() with keys() to avoid
hash iterator state bugs, and made sure that keys are sorted where
their order might matter, which was as far as I could tell only in
how proxy configuration was read from the envrionment.
There was ambiguity as to which of $ENV{http_proxy} and
$ENV{HTTP_PROXY} would be chosen by LWP::UserAgent->env_proxy(). We now
choose HTTP_PROXY if both are set, and if they differ we warn about
the conflicting configuration.
This patch includes tests to check that we warn on conflicting config
and that we correctly handle setting via either.
This includes a version …

Fix RT #81381 - Make LWP::UserAgent robust to 5.17.6/5.18 hash randomization

---

Changes
cpanfile

This PR does two things:
* Fix #374. Requires HTTP::Daemon 6.12
* HTTP::Daemon is used only in `t/*.t`. So change it from runtime-require to test-require.

require HTTP::Daemon 6.12 for test

---

lib/LWP/UserAgent.pm

See https://perlmonks.org/?node_id=11132138 , which is weird code
and shouldn't fail, but maybe fails in persistent environments
like Apache.

Be explicit in the prerequisite of HTTP::Status

---

lib/LWP/UserAgent.pm
t/base/default_content_type.t

If you set up a default_header('Content-Type => '...') but then
do ->post($url, 'Content-Type' => 'foo', Content => "..."), the
provided content type should override the default!
We only override the default if the provided value is truthy though,
as this mirrors how ->post($url, "Content-Type" => 0) behaves.
This fixes a bug in my initial implementation in #100

When a truthy Content-Type is provided, override the default

---

Changes
t/base/ua_handlers.t

Seems like quite a novel feature that's worthy of a test.
I tweaked `t/base/ua_handlers.t` slightly to ensure each subtest gets it's own UA to avoid shared state.
This change should slightly increase code coverage :tada:

Add a test for "response_redirect"

---

Changes
META.json
bin/lwp-request
cpanfile
lib/LWP/Authen/Digest.pm
lib/LWP/Debug/TraceHTTP.pm
lib/LWP/MemberMixin.pm
lib/LWP/Protocol.pm
lib/LWP/Protocol/cpan.pm
lib/LWP/Protocol/data.pm
lib/LWP/Protocol/file.pm
lib/LWP/Protocol/ftp.pm
lib/LWP/Protocol/gopher.pm
lib/LWP/Protocol/http.pm
lib/LWP/Protocol/loopback.pm
lib/LWP/Protocol/mailto.pm
lib/LWP/Protocol/nntp.pm
lib/LWP/Protocol/nogo.pm
lib/LWP/RobotUA.pm
lib/LWP/UserAgent.pm
t/local/http.t
t/local/httpsub.t
t/local/protosub.t
xt/author/live/jigsaw/auth-b.t
xt/author/live/jigsaw/auth-d.t

Base says 
> Unless you are using the fields pragma, consider this module discouraged in favor of the lighter-weight parent.
We aren't using fields so let's follow their advice, parent is also core in 5.10+.
We were already using parent in one place (Protocol::http) though it was undeclared in our deps so this fixes that. Depend on the minimum version to support `-norequire`.

Replace remaining uses of "base" with "parent"

---

lib/LWP/UserAgent.pm

No longer useful after related linefeeds were removed in 21bfce4df2767929b79e15b3dc4c27db211772a4.

Remove unnecessary string concatenations in mirror error messages

---

dist.ini

Locale settings affect the choice of aspell's dictionary unless one is explicitly set.
Refs https://github.com/libwww-perl/libwww-perl/pull/393#issuecomment-970301100

Use American English aspell master dictionary for POD spelling tests

---

Changes
lib/LWP/UserAgent.pm

Closes #395.
Logging what was the timestamp we tried to set could be useful. No strong opinions whether to do that and how to format it in the error message; suggestions welcome, and actually feel free to modify this branch directly, no need to run that by me :)

Warn if updating modification time of mirrored file fails

---

cpanfile

Require Getopt::Long at runtime, too

---

Changes
lib/LWP/Protocol.pm
lib/LWP/Simple.pm
lib/LWP/UserAgent.pm
t/local/download_to_fh.t

By checking that it "looks like a name" as well as if it is an openhandle.  If it is a filehandle, we "dup" it instead of opening directly.
This allows us to avoid some possible race conditions and should resolve #362 and be able to use the more secure idiom in #393 .  I think it would also cause the problem described in #292 to no longer error.

Allow downloading to a filehandle

---

Changes
lib/LWP/UserAgent.pm
t/local/http.t

Satisfies #239
I noticed two existing issues with the headparser code, neither of which I have addressed in this commit:
1. https://github.com/libwww-perl/libwww-perl/issues/196)
2. Noscript tags are valid within the head tag, and they can contain meta tags. So it's possible to have two sets of contradictory meta tags. We can either:
* ignore noscript: `$parser->ignore_elements('noscript');`
* or distinguish the meta tags found in noscript by prefixing/suffixing them so the user can choose which to use.

meta refresh redirect

---

dist.ini

Due to history, the name of this dist does not match the name of its
primary module, or even any module included. The NAME in the Makefile.PL
needs to match the actual primary module of the dist, but the name of
the dist should not be changed. Dist::Zilla on its own does not provide
a way for these to diverge, but the [MakeMaker::Awesome] plugin does
allow passing in arbitrary additional options. Adding our own NAME
option should override the default provided option, even if both still
end up in the Makefile.PL.

fix NAME in Makefile.PL

---

Changes
lib/LWP/UserAgent.pm
t/local/http.t

- Revert "Remove unused variable introduced in 9d73bc422"
- Revert "Add tests for meta_refresh + max_redirects"
- Revert "Preserve the Refresh header on meta redirect"
- Revert "Add tests for meta refresh redirects"
- Revert "Handle meta refresh redirects"
This also broke WWW::Mechanize::Cached: https://github.com/libwww-perl/WWW-Mechanize-Cached/issues/27
From #toolchain on irc.perl.org
```
Could I get some feedback on https://github.com/libwww-perl/WWW-Mechanize-Cached/pull/28 Specifically https://github.com/libwww-perl/WWW-Mechanize-Cached/pull/28/commits/ab875678759d66300d772e33e19d76d143970ed4
I was getting "Can't store CODE items" errors from Storable when caching HTTP::Response objects.
feels wrong
LWP is leaving a handler in place unexpectedly, when it removes others
also, the PR …
```

Revert automatic follow of meta refresh tags

---

Changes
lib/LWP.pm

The same functionality can be achieved with either $LWP::VERSION or LWP->VERSION.

Remove undocumented LWP::Version sub

---

cpanfile
dist.ini
t/base/default_content_type.t

The dynamic dependency on HTTP::Status was meant to avoid one known problematic version. But upgrading HTTP::Status is not an onerous requirement. Simplify the config and dependencies by just requiring the new working version.

remove dynamic dependency on HTTP::Status

---

.github/dependabot.yml
.github/workflows/dzil-build-and-test.yml

- Run CI on 5.36 and 5.38
- Only run CI on push when branch is master
- Remove scheduled CI as it can disable the action after inactivity
- Add dependabot to upgrade actions

Update CI settings

---

Changes
lib/LWP/Protocol/http.pm

More details are at https://github.com/libwww-perl/libwww-perl/issues/449

Making it possible to use IPv6 in https call through https proxy environment (in case of using CONNECT method to create a tunnel)

---

Changes
lib/LWP/Protocol/http.pm
lib/LWP/UserAgent.pm

Since LWP 6.00 in 2011 we require Perl v5.8.8 or better which makes these checks redundant.

Simplify code slightly for Perl v5.8+

---

.github/dependabot.yml
.github/workflows/dzil-build-and-test.yml

- **Add 5.40 to GH actions**
- **Drop 5.14 from Windows GH actions**
- **Add dependabot config**
- **bump GH actions Ubuntu from 20.04 to 24.04**

Update GH actions

---

lib/LWP/UserAgent.pm

Upon upgrading from perl 5.36.1 to perl 5.40.1, this error started showing up:
```
Unrecognized LWP::UserAgent options: proxy at /path/to/my/site_perl/5.40.1/LWP/UserAgent.pm line 102.
```
Sure enough, the `new` method seems to very clearly expect for `%cnf` to be empty before ever checking for `$cnf{proxy}`. I'm confused as to how nobody seems to have been hitting this previously.

don't warn on proxy as unrecognized option for LWP::UserAgent->new

---

README.md
lib/LWP/UserAgent.pm

[Some security vendors are considering `proxy[.]my[.]place` a malicious domain](https://www.virustotal.com/gui/domain/proxy.my.place/detection), causing `UserAgent.pm` to get flagged as potential malware by their scans. Updating the example documentation in `UserAgent.pm` and the `README` that includes this domain to avoid any confusion.

Remove example references to malicious domain
