libwww-perl/libwww-perl

lib/LWP.pm
Minor POD warning fixed in LWP.pm
=> Fixed minor POD warning

t/base/ua.t
Added tests covering the issue reported in #50 which apparently has been fixed.
=> Test whether $UA->post() and $UA->put() accept hashes or arrays

Changes, lib/LWP/UserAgent.pm, t/base/ua.t
=> Allow setting of proxy and no_proxy from the constructor of LWP::UA

Changes, bin/lwp-download
=> Improve lwp-download --help

t/local/http.t
Added a couple of environment variables to allow the tests to be run
manually to help with debugging.  Simply increasing the timeout on the
test server ought to make it easier to debug.  Allowing you to manually
split out the test run so you can run the 2 parts separately ought to
allow you to run them each in the debugger if necessary.
To run them discretely run the server like this,
PERL_LWP_ENV_HTTP_TEST_SERVER_TIMEOUT=10000 perl -I lib t/local/http.t \
daemon
Then the tests like this,
PERL_LWP_ENV_HTTP_TEST_URL=http://127.0.0.1:56957/ perl -I lib \
t/local/http.t
Alternatively to just stop the server from timeing out too soon run the
tests like this,
PERL_LWP_ENV_HTTP_TEST_SERVER_TIMEOUT=10000 perl -I lib t/local/http.t
=> Added a developer feature to the http.t tests.

lib/LWP/Protocol/http.pm, lib/LWP/UserAgent.pm, t/local/http.t
=> add send_te configuration to disable sending the TE header

lib/LWP/Debug.pm
=> Suggest LWP::ConsoleLogger as an alternative to the deprecated LWP::Debug

README.md, lib/LWP/UserAgent.pm
=> Add response details to timeout() documentation

Changes, lib/LWP/UserAgent.pm, t/base/ua_handlers.t
=> improve handler documentation

cpanfile
=> Update Net::HTTP from 6.07 to 6.18

Changes, lib/LWP/Authen/Basic.pm, lib/LWP/Authen/Digest.pm, t/local/http.t
This is a re-worked version of #313.  Mostly just messing with Git history and then tidying.
=> Squashed and rebased pr 313

README.md, lib/LWP/UserAgent.pm, t/base/ua.t
=> Fix docs to match keep_alive => undef behavior, add some trivial tests

Changes, lib/LWP/UserAgent.pm, t/local/http.t
Original code by @romangaleev. I've added tests. See  #78 for details.
Closes  #78.
=> FIX: continue challenge schemes

lib/LWP/Authen/Basic.pm, t/local/http.t
https://tools.ietf.org/html/rfc7617#section-2.1
=> Support basic authentication charset per RFC 7617

Changes, lib/LWP/UserAgent.pm, t/redirect.t
Rebased work by @augwa onto current master and added tests.
Fixes #171 
Closes #303
=> Fix Client-Warning: Internal response sometimes reset (fixup)

.github/workflows/dzil-build-and-test.yml
This makes use of some new helper scripts that I'm working on: https://github.com/oalders/github-perl-helpers/blob/master/bin/auto-build-and-test-dist
=> Add GitHub workflows

.github/workflows/dzil-build-and-test.yml, lib/LWP/UserAgent.pm, t/local/http.t
This commit is basically a copy of @preaction's work. I just had trouble
cherry-picking his commit into the repository.
Closes #5
=> Only add cookies from the jar if there aren't cookies in the request

.github/workflows/dzil-build-and-test.yml, cpanfile, t/base/ua.t
=> Fix proxy test on Windows

Changes, lib/LWP/Authen/Digest.pm
=> Remove block of code which creates message-digest auth request field

Changes, t/redirect.t
See https://github.com/libwww-perl/libwww-perl/issues/370#issuecomment-859909166 for discussion.
=> Attempt to avoid rare fails in redirect.t

Changes, t/base/proxy.t
Before doing changes to fix #372 it is good to have a
complete test coverage of env_proxy().
=> increase test coverage for env_proxy()

Changes, lib/LWP/UserAgent.pm
=> Remove unused variable introduced in 9d73bc422

cpanfile
See https://rt.cpan.org/Public/Bug/Display.html?id=146701
This does not address the entire issue, but it's a start.
=> Raise minimum version of HTML::HeadParser to 3.71

Changes, lib/LWP/UserAgent.pm, t/base/proxy_request.t
=> don't allow partial matches for proxy domain names #421

Changes, cpanfile, dist.ini, lib/LWP/UserAgent.pm, t/local/cookie_jar.t
This adds the interface @oalders suggested in #91 to the code @tomhukins wrote originally. 
Closes #91.
=> Resubmit PR 91

Changes, lib/LWP/UserAgent.pm
=> Use rather than require Module::Load

.github/workflows/dzil-build-and-test.yml, Changes, lib/LWP/UserAgent.pm, t/base/proxy_request.t
Fix for issue #433, including tests.
=> Fix no_proxy subdomain matching

lib/LWP/UserAgent.pm
Closes https://github.com/libwww-perl/libwww-perl/issues/309
=> Document that disabling the UA timeout is not supported

Changes, lib/LWP/UserAgent.pm
=> document mirror throwing exception #470

t/leak/no_leak.t
=> Test on example.com rather than neverssl.com
